id: P007041
initial_creation_type: ocr
created_at: 30/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W4CZ65554
  title: དཀར་མོ་གཡས་འཁྱིལ་དགོན་གྱི་ཆོས་སྤྱོད།
  author: ''
  volumes:
    99d416583be44696888f3b7bf62af3c5:
      image_group_id: I4CZ65585
      title: Volume 1 of dkar mo g.yas 'khyil dgon gyi chos spyod/
      volume_number: 1
      total_pages: 362
      base_file: v001.txt
