id: opecha:P007041
initial_creation_type: ocr
source_metadata:
  id: bdr:W4CZ65554
  title: དཀར་མོ་གཡས་འཁྱིལ་དགོན་གྱི་ཆོས་སྤྱོད།
  volume:
    99d416583be44696888f3b7bf62af3c5:
      image_group_id: I4CZ65585
      title: Volume 1 of dkar mo g.yas 'khyil dgon gyi chos spyod/
      volume_number: 1
      total_pages: 362
  author: ''
ebook_metadata:
  title: དཀར་མོ་གཡས་འཁྱིལ་དགོན་གྱི་ཆོས་སྤྱོད།
  author: ''
  sku: P007041
  cover: cover.jpg
  layers:
  - pagination
