id: P007041
initial_creation_type: ocr
source_metadata:
  id: bdr:W4CZ65554
  title: དཀར་མོ་གཡས་འཁྱིལ་དགོན་གྱི་ཆོས་སྤྱོད།
  author: ''
  volumes:
    843c60a007544d88afb8509ed189f88d:
      image_group_id: I4CZ65585
      title: ''
      volume_number: 1
      total_pages: 362
ebook_metadata:
  title: དཀར་མོ་གཡས་འཁྱིལ་དགོན་གྱི་ཆོས་སྤྱོད།
  author: ''
  sku: P007041
  cover: cover.jpg
  layers:
  - pagination
