id: I84878D4A
legacy_id: P007041
ocr_import_info:
  bdrc_scan_id: W4CZ65554
  source: bdrc
  ocr_info:
    timestamp: '2020-03-30T03:29:38'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-03T20:55:42.913790+00:00'
last_modified: 2022-09-04 04:55:52.586041
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W4CZ65554
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW4CZ65554
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: དཀར་མོ་གཡས་འཁྱིལ་དགོན་གྱི་ཆོས་སྤྱོད།
statistics:
  ocr_word_mean_confidence_index: 0.5101528513766868
  ocr_word_median_confidence_index: 0.47999998927116394
quality: null
bases:
  I4CZ65585:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4CZ65585
      total_pages: 362
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I4CZ65585.txt
    statistics:
      ocr_word_median_confidence_index: 0.47999998927116394
      ocr_word_mean_confidence_index: 0.5101528513766868
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
